
name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: alpine-3.23

    steps:
      - name: Install dependencies
        run: |
          apk add --no-cache nodejs npm git curl tar

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
          github-server-url: https://git.kcfam.us

      - name: Build
        run: npm ci && npm run build

      - name: Deploy
        run: |
          echo "Copying build to /sites/test-track"
          mkdir -p /sites/test-track
          rm -rf /sites/test-track/*
          cp -vr dist/. /sites/test-track/

